[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run --filter @chotter/api build"]

[start]
cmd = "bun run --filter @chotter/api start"
